# Generated by Django 4.2.1 on 2023-06-15 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_menus', '0002_alter_menu_menu_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-menu_title']},
        ),
        migrations.AlterModelTable(
            name='menu',
            table='restro_menus',
        ),
    ]
